### PR TITLE
Get rid of package downgrade warnings

### PR DESCRIPTION
**Pull request by dougbu**
- make System.Collections.Immutable match what System.Reflection.Metadata pulls in
- make System.Runtime.Serialization.Primitives match what Newtonsoft.Json pulls in

### CODE REVIEW

**Comment by pakrym** [comment]
Does it work using VS's msbuild (that runs on full framework)?

**Comment by dougbu** [comment]
> Does it work using VS's msbuild (that runs on full framework)?

Yes. No errors or warnings when building in vs nor when running `msbuild.exe` on the command line.

**Comment by pakrym** [comment]
What about when defining `/p:EnableFindUnusedReferences=true`, I'm asking because it took me some time to align assembly references used by Reflection.Metadata when I was writing it.

**Comment by dougbu** [comment]
> when defining `/p:EnableFindUnusedReferences=true`

That causes errors in my branch as well as `dev`. Nothing related to unused references. Looks like the task has some issues e.g.
```
C:\dd\dnx\Universe++\BuildTools\src\Internal.AspNetCore.Sdk\build\FindUnusedReferences.targets(10,5): error MSB4036: The "Sdk_FindUnusedReferences" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Users\dougbu\.dotnet\x64\sdk\2.0.0-preview2-006071" directory. [C:\dd\dnx\Universe++\BuildTools\src\PackageClassifier\PackageClassifier.csproj]
```

> I'm asking because it took me some time to align assembly references used by Reflection.Metadata when I was writing it.

Dependencies change, especially as our TFMs change.

**Comment by pakrym** [comment]
This flag is not supposed to be used on BuildTools repo itself, it's used when building another repo. And if you try running packages build out you branch to build kestrel with /p:EnableFindUnusedReferences=true it would fail with assembly version mismatch:

```
> & "c:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" /t:Build /p:EnableFindUnusedReferences=true


(FindUnusedReferences target) ->
  C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018: The "Sdk_FindUnusedReferences" task failed unexpectedly.\r [D:\github\aspnet\KestrelHttpServer\ src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.Immutable, V ersion=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.\r [D:\github\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstra ctions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018: File name: 'System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f 7f11d50a3a'\r [D:\github\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018:    at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions option s, Int32 size)\r [D:\github\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018:    at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream)\r [D:\github\aspnet\Ke strelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018:    at Microsoft.AspNetCore.BuildTools.Sdk_FindUnusedReferences.Execute()\r [D:\github\aspnet\Kest relHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execut e()\r [D:\github\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()\r [D:\github\ aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
C:\Users\pakrym\.nuget\packages\internal.aspnetcore.sdk\2.1.0-rc2-t0047703cf\build\FindUnusedReferences.targets(10,5): error MSB4018: \r [D:\github\aspnet\KestrelHttpServer\src\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstract ions\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.csproj]
```
While `dev` version runs without any errors.

**Comment by dougbu** [comment]
Ah, these task projects aren't built correctly. The published packages only contain the necessary files for .NET Framework 4.6. None of the following project elements are working as expected for .NET Standard 1.6:
``` xml
<PackageReference Include="..." Version="..." PrivateAssets="All" />
```

Let's look at this tomorrow.

**Comment by dougbu** [comment]
:up::date: as discussed offline

**Comment by dougbu** [comment]
da73e10

**Pull request closed without merging**
