### PR TITLE
Allow yml files to specify build directory

### PR DESCRIPTION
**Pull request by jkotalik**
When running CI builds in aspnetcore, we need a way to run build.cmd inside of a subfolder.

I am open for suggestions to make this more robust.

### CODE REVIEW

**Comment by natemcmaster** [comment]
This solution is fine, but I'm wondering if we should take it a step further and allow callers to replace the build.sh/cmd step altogether. Thoughts?

**Comment by jkotalik** [comment]
I'd be okay with that. However, I'm noticing we probably need to use the buildDirectory for uploading artifacts: https://dnceng.visualstudio.com/public/_build/results?buildId=38899&view=logs (or we can disable upload artifact for CI builds).

**Comment by jkotalik** [comment]
Chatted offline, closing in favor of copying the yml files to mondo repo.

**Comment by jkotalik** [comment]
Chatted offline, we are moving these files to aspnetcore.

**Pull request closed without merging**
