### PR TITLE
Update SDK to 2.2.0-preview1-008003

### PR DESCRIPTION
**Pull request by natemcmaster**
Includes changes require for dotnet-cli global tools

### CODE REVIEW

**Comment by natemcmaster** [comment]
not sure. I need it for dotnet-watch changes

**Comment by rynowak** [comment]
👏 👏 👏 👏 👏 👏 👏 👏

**Comment by rynowak** [comment]
I'll try this out and let you know.

**Comment by rynowak** [comment]
```
Build started 1/24/2018 5:53:07 PM.
     1>Project "C:\Users\Ryan\.dotnet\buildtools\korebuild\2.1.0-preview1-15681\KoreBuild.proj" on node 1 (UpgradeDepend
encies target(s)).
     1>C:\Users\Ryan\.dotnet\buildtools\korebuild\2.1.0-preview1-15681\modules\KoreBuild.Tasks\module.targets(105,5): er
ror MSB4018: The "UpgradeDependencies" task failed unexpectedly. [C:\Users\Ryan\.dotnet\buildtools\korebuild\2.1.0-previ
ew1-15681\KoreBuild.proj]
```

lel

**Comment by rynowak** [comment]
This doesn't have the changes I need. @vijayrkn do you have any idea what build would have our changes?

**Comment by natemcmaster** [comment]
They changed versioning to 2.1.300-preview1-XYZ shortly after branching for 2.1, but they haven't produced public builds for that branch yet.

**Comment by natemcmaster** [comment]
@rynowak is there stack trace on the error?

**Comment by vijayrkn** [comment]
@rynowak  This build has the changes - dotnet-sdk-2.1.300-preview2-008017

**Comment by rynowak** [comment]
We need the precompilation change to get into preview1. I thought that was clear sorry. Let's discuss this tomorrow.

**Comment by vijayrkn** [comment]
you can ignore the 'preview2' in version number. Preview1 builds should also have the change.

**Comment by rynowak** [comment]
OK cool, so  dotnet-sdk-2.1.300-preview1-008017 or newer then 👍

**Pull request merged**
