### PR TITLE
Remove DefaultCompositeRule from SigningVerificationCompositeRule

### PR DESCRIPTION
**Pull request by ajaybhargavb**
https://github.com/aspnet/Coherence-Signed/issues/574

We want to run all the non-signing verification rules separately.

@pranavkm @natemcmaster @Eilon

### CODE REVIEW

**Comment by natemcmaster** [comment]
I assume there will be changes to Coherence-Signed as well?

**Comment by ajaybhargavb** [comment]
Yes

**Comment by natemcmaster** [comment]
Change looks fine. If you need this done for 2.0.0, merge this to rel/2.0.0 instead (and merge back to dev).

**Comment by ajaybhargavb** [comment]
This is merged

**Pull request closed without merging**
