### PR TITLE
Add common external package version variables

### PR DESCRIPTION
**Pull request by BrennanConroy**
@mikaelm12 @pranavkm @natemcmaster

### CODE REVIEW

**Comment by natemcmaster** [comment]
What will be the corresponding change for something that consumes the Internal.AspNetCore.Sdk project, like aspnet/Common?

**Comment by pranavkm** [comment]
@natemcmaster - we're going to update individual repos to include this value. I guess we can do that once this package builds.

**Comment by mikaelm12** [comment]
😄

**Comment by natemcmaster** [comment]
I don't think that'll work. The package isn't installed when you run restore for the first time.

**Comment by natemcmaster** [comment]
Recommend either creating Internal.AspNetCore.Test.Sdk which depends on the xunit version we need, or waiting until https://github.com/Microsoft/msbuild/issues/1493 is ready

**Pull request closed without merging**
