### PR TITLE
Call the right function in the bash script

### PR DESCRIPTION
**Pull request by davidfowl**
Found this while trying to make a minimal docker dev env for ASP.NET Core

### CODE REVIEW

**Comment by natemcmaster** [comment]
Normally when we update this script we copy it to all repos except aspnet/Universe (it has customization for ProdCon).

**Comment by davidfowl** [comment]
> Normally when we update this script we copy it to all repos except aspnet/Universe (it has customization for ProdCon).

ZOMG, I'll just merge this 😄

**Comment by davidfowl** [comment]
@ryanbrandenburg I hope we have a bot for that.

**Comment by natemcmaster** [comment]
We don’t have a bot for it because it happens rarely enough that automation isn’t worth the effort.

**Pull request merged**
