### PR TITLE
Better logging and more skips for StrongName

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
Bump the importance of messages from these tasks so we actually see them, and include more assemblies to the list of things we'll actually skip.

### CODE REVIEW

**Comment by natemcmaster** [comment]
> Bump the importance of messages from these tasks so we actually see them

Did you try `/verbosity:normal`?

**Comment by ryanbrandenburg** [comment]
You can also make it visible by changing the verbosity, but since these messages are the core of what we're doing in this target I felt they warranted high importance so that they're always visible.

**Comment by natemcmaster** [comment]
As a rule of thumb, I'm in favor of minimal output where possible, and I don't think these messages make the cut for "high" importance, especially if we start running the targets on every build....but not worth blocking this PR on that so :shipit:

**Comment by natemcmaster** [comment]
Side note: the High/Medium verbosity issue is less important in the context of #345 where CI logs will default to `/verbosity:normal` and produce blocks that make CI output more readable.

image

**Comment by ryanbrandenburg** [comment]
:up::date:

**Pull request merged**
