### PR TITLE
Update SDK to 3.0.100-alpha1-009701

### PR DESCRIPTION
**Pull request by natemcmaster**

### CODE REVIEW

**Comment by natemcmaster** [comment]
There are some bizarre InvalidCastException's during unit tests. https://dnceng.visualstudio.com/public/_build/results?buildId=27506&view=ms.vss-test-web.test-result-details
```
error : Unable to cast object of type 'System.Linq.EmptyPartition`1[Microsoft.Build.Evaluation.Project]' to type 'System.Collections.Generic.IList`1[Microsoft.Build.Evaluation.Project]'.
```

@rainersigwald @dsplaisted - can you think of any changes in MSBuild in the 3.0.100-* nightly SDK builds that would cause these errors? If not, there may be a bug in LINQ in .NET Core 3.0.

**Comment by rainersigwald** [comment]
I'm pretty sure we're currently shipping the same MSBuild bits in 3.0 as 2.1 at the moment, so I wouldn't expect it to be MSBuild.

**Comment by natemcmaster** [comment]
Fun. I'll check with the corefx team then.

**Comment by natemcmaster** [comment]
```
Unable to cast object of type 'System.Linq.EmptyPartition`1[Microsoft.Build.Evaluation.Project]' to type 'System.Collections.Generic.IList`1[Microsoft.Build.Evaluation.Project]'.
   at Microsoft.Build.Evaluation.ProjectCollection.LoadedProjectCollection.GetMatchingProjectsIfAny(String fullPath) in E:\A\_work\82\s\src\Build\Definition\ProjectCollection.cs:line 2394
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(String fullPath) in E:\A\_work\82\s\src\Build\Definition\ProjectCollection.cs:line 1024
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.GetProject(String path, ProjectCollection projectCollection, Boolean policyDesignBuild) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 109
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.Create(String path, Boolean policyDesignBuild) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 70
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.<>c__DisplayClass2_0.<CreateMany>b__2(String projectFile) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 54

**Comment by rainersigwald** [comment]
hmm, that does look suspicious and was touched semi-recently in MSBuild. I'm looking harder.

**Comment by natemcmaster** [comment]
I updated the build to MSBuild 15.8.166, and still get the same error. Slightly different line number.

During unit tests...
```
typeof(ProjectCollection).Assembly.Location
"C:\\Users\\namc\\.nuget\\packages\\microsoft.build\\15.8.166\\lib\\netcoreapp2.1\\Microsoft.Build.dll"
```

```
Unable to cast object of type 'System.Linq.EmptyPartition`1[Microsoft.Build.Evaluation.Project]' to type 'System.Collections.Generic.IList`1[Microsoft.Build.Evaluation.Project]'.
   at Microsoft.Build.Evaluation.ProjectCollection.LoadedProjectCollection.GetMatchingProjectsIfAny(String fullPath) in /_/src/Build/Definition/ProjectCollection.cs:line 2334
   at Microsoft.Build.Evaluation.ProjectCollection.GetLoadedProjects(String fullPath) in /_/src/Build/Definition/ProjectCollection.cs:line 986
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.GetProject(String path, ProjectCollection projectCollection, Boolean policyDesignBuild) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 109
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.Create(String path, Boolean policyDesignBuild) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 70
   at KoreBuild.Tasks.ProjectModel.ProjectInfoFactory.<>c__DisplayClass2_0.<CreateMany>b__2(String projectFile) in C:\src\aspnet\BuildTools\modules\KoreBuild.Tasks\Internal\ProjectModel\ProjectInfoFactory.cs:line 54
```

**Comment by rainersigwald** [comment]
Possibly related to https://github.com/dotnet/corefx/pull/31025, @stephentoub? The code in msbuild is doing

```c#
                    return candidates ?? (IList<Project>)Enumerable.Empty<Project>();
```

which is then getting this cast exception?

**Comment by natemcmaster** [comment]
Yup, that's it. Let's see what the runtime team says about https://github.com/dotnet/corefx/issues/32645.

**Comment by natemcmaster** [comment]
Blocked on https://github.com/Microsoft/msbuild/issues/3834

**Comment by rainersigwald** [comment]
Note: blocked on the fix for that (easy) and ingesting a fixed build to the 3.0 flow (somewhat harder since we haven't done it yet).

**Comment by natemcmaster** [comment]
I see that the fix for the MSBuild error was merged into Microsoft/MSBuild a while ago, but I still see this error with the latest nightly, 3.0.100-alpha1-009695. @dsplaisted - how do we go about getting the MSBuild fix into a 3.0 build?

**Comment by livarcocc** [comment]
we just need to update the MSBuild version on dotnet/toolset, assuming we have a build for it.

**Pull request merged**
