### PR TITLE
Update SDK to 2.1.300-preview2-008407

### PR DESCRIPTION
**Pull request by jbagga**

### CODE REVIEW

**Comment by natemcmaster** [comment]
Looks like there may be some issue with this SDK. PR builds on Travis are failing. Do you have a Linux or macOS box to try this update on your own?

**Comment by natemcmaster** [comment]
Peeling the onion. The next error is this. NuGet made breaking API changes again.
```
 C:\Users\namc\AppData\Local\Temp\korebuild\p4mqoz4d.srh\build\repo.targets(25,5): error : Method not found: 'System.Threading.Tasks.Task NuGet.Protocol.Core.Types.PackageUpdateResource.Push(System.String, System.String, Int32, Boolean, System.Func`2<System.String,System.String>, System.Func`2<System.String,System.String>, NuGet.Common.ILogger)'. [C:\Users\namc\.dotnet\buildtools\korebuild\2.1.0-preview2-t000\KoreBuild.proj]
 C:\Users\namc\AppData\Local\Temp\korebuild\p4mqoz4d.srh\build\repo.targets(25,5): error :    at KoreBuild.Tasks.PushNuGetPackages.PushPackageAsync(PackageUpdateResource packageUpdateResource, PackageInfo package) [C:\Users\namc\.dotnet\buildtools\korebuild\2.1.0-preview2-t000\KoreBuild.proj]
 C:\Users\namc\AppData\Local\Temp\korebuild\p4mqoz4d.srh\build\repo.targets(25,5): error :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) [C:\Users\namc\.dotnet\buildtools\korebuild\2.1.0-preview2-t000\KoreBuild.proj]
 C:\Users\namc\AppData\Local\Temp\korebuild\p4mqoz4d.srh\build\repo.targets(25,5): error :    at KoreBuild.Tasks.PushNuGetPackages.PushPackageAsync(PackageUpdateResource packageUpdateResource, PackageInfo package) [C:\Users\namc\.dotnet\buildtools\korebuild\2.1.0-preview2-t000\KoreBuild.proj]
 C:\Users\namc\AppData\Local\Temp\korebuild\p4mqoz4d.srh\build\repo.targets(25,5): error :    at KoreBuild.Tasks.PushNuGetPackages.PushPackagesAsync(PackageUpdateResource packageUpdateResource) in C:\dev\aspnet\BuildTools\modules\KoreBuild.Tasks\PushNuGetPackages.cs:line 107 [C:\Users\namc\.dotnet\buildtools\korebuild\2.1.0-preview2-t000\KoreBuild.proj]  C:\Users\namc\AppData\Local\Temp\korebuild\p4mqoz4d.srh\build\repo.targets(25,5): error :    at KoreBuild.Tasks.PushNuGetPackages.PublishToFeedAsync() in C:\dev\aspnet\BuildTools\modules\KoreBuild.Tasks\PushNuGetPackages.cs:line 100 [C:\Users\namc\.dotnet\buildtools\korebuild\2.1.0-preview2-t000\KoreBuild.proj]
 C:\Users\namc\AppData\Local\Temp\korebuild\p4mqoz4d.srh\build\repo.targets(25,5): error :    at KoreBuild.Tasks.PushNuGetPackages.Execute() in C:\dev\aspnet\BuildTools\modules\KoreBuild.Tasks\PushNuGetPackages.cs:line 76 [C:\Users\namc\.dotnet\buildtools\korebuild\2.1.0-preview2-t000\KoreBuild.proj]
```

**Comment by natemcmaster** [comment]
Found it: https://github.com/NuGet/NuGet.Client/pull/2043. The made a breaking API change again.

**Comment by pranavkm** [comment]
@natemcmaster could we bump this to 8407? It has a Razor Sdk change we need to fix templates.

**Comment by natemcmaster** [comment]
>  It has a Razor Sdk change we need to fix templates.

We need to find ways to make these kinds of changes that doesn't involve round-tripping to the CLI. We're currently not able to move our CLI forward because this is apparently causing our own build to fail. From what I hear, it's blocking both @ajaybhargavb and @jbagga from doing templates testing. Cyclical dependencies like this are not good.

**Comment by ajaybhargavb** [comment]
I need it only because there is a bug fix in corefx that is needed for Razor build server to work.

**Comment by natemcmaster** [comment]
Fortunately, you should be able to update to new runtime builds independent from SDK updates to our build tools

**Comment by natemcmaster** [comment]
On my machine, I'm not able to use 8407. Something is either wrong in MSBuild, the LZMA, or something else.
```
/Users/namc/.dotnet/sdk/2.1.300-preview2-008407/Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3106: Assembly strong name "/Users/namc/.dotnet/sdk/NuGetFallbackFolder/system.security.principal.windows/4.4.0/ref/netstandard2.0/System.Security.Principal.Windows.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
```

**Comment by pranavkm** [comment]
> We need to find ways to make these kinds of changes that doesn't involve round-tripping to the CLI

For most product code we have a way to work around this. But there's not a very good way to do this with the templates unless we choose to have the template be different than what `dotnet new` produces. That said, the hope is that once we ship a version of the Razor Sdk, we'll have much less churn requiring these sort of round trips.

**Comment by natemcmaster** [comment]
Must have been something weird in the LZMA. Blew away all of my caches and installations and now things build locally. I updated this to use 8407

**Comment by pranavkm** [comment]
Thanks!

**Comment by jbagga** [comment]
@natemcmaster Does this need to be merged back to dev?

**Comment by natemcmaster** [comment]
Actually, it's not passing on CI, so we probably need to revert this

**Pull request merged**
