### PR TITLE
Flow BuildNodeJs when calling custom restore targets

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by natemcmaster** [comment]
Discussed over chat. Not sure if this is necessary because BuildNodeJS should be a global property. Waiting for more debugging info to confirm...

**Comment by javiercn** [comment]
I just added code to print the variables. Will they show up in the console/log for nested msbuild calls? If I get confirmation I'll close this.

**Comment by natemcmaster** [comment]
They will show up in console logging if you also set `Importance="high"` on the `<Message>` task. Regardless of logging level, the message should appear in the binlog.

**Comment by natemcmaster** [comment]
Ok to close? I don't think we're planning to merge this.

**Comment by JunTaoLuo** [comment]
I'm closing this since there hasn't been any activity for a while now. Please reopen if this is still needed.

**Comment by AMARNATH-ORG** [comment]
ok

**Pull request closed without merging**
