### PR TITLE
Update VersionTool to warn of required changes after patch and pack t…

### PR DESCRIPTION
**Pull request by JunTaoLuo**
…ool binaries in nupkg

fyi @pranavkm

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Sample output:

```
...
 **************************************************************************
  * Updates for patch have been made. Please commit the following changes. *
  **************************************************************************
  Non-SRC project files modified in Common. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Common.
  SRC project files modified in Testing. Please create branch rel/1.0.2 and merge the changes in C:\gh\Coherence-Patch/.repositories/Testing.
  Non-SRC project files modified in DependencyInjection. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/DependencyInjection.
  Non-SRC project files modified in FileSystem. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/FileSystem.
  Non-SRC project files modified in JsonPatch. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/JsonPatch.
  Non-SRC project files modified in Microsoft.Data.Sqlite. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Microsoft.Data.Sqlite.
  Non-SRC project files modified in Configuration. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Configuration.
  Non-SRC project files modified in EventNotification. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/EventNotification.
  Non-SRC project files modified in Logging. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Logging.
  Non-SRC project files modified in Options. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Options.
  Non-SRC project files modified in Caching. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Caching.
  Non-SRC project files modified in HtmlAbstractions. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/HtmlAbstractions.
  Non-SRC project files modified in HttpAbstractions. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/HttpAbstractions.
  SRC project files modified in Hosting. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/Hosting.
  Non-SRC project files modified in Razor. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Razor.
  SRC project files modified in DataProtection. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/DataProtection.
  SRC project files modified in EntityFramework. Please create branch rel/1.0.4 and merge the changes in C:\gh\Coherence-Patch/.repositories/EntityFramework.
  SRC project files modified in KestrelHttpServer. Please create branch rel/1.0.4 and merge the changes in C:\gh\Coherence-Patch/.repositories/KestrelHttpServer.
  SRC project files modified in WebListener. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/WebListener.
  Non-SRC project files modified in BasicMiddleware. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/BasicMiddleware.
  SRC project files modified in IISIntegration. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/IISIntegration.
  Non-SRC project files modified in CORS. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/CORS.
  SRC project files modified in Localization. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/Localization.
  SRC project files modified in ResponseCaching. Please create branch rel/1.0.2 and merge the changes in C:\gh\Coherence-Patch/.repositories/ResponseCaching.
  Non-SRC project files modified in Routing. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Routing.
  Non-SRC project files modified in ServerTests. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/ServerTests.
  SRC project files modified in Session. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/Session.
  SRC project files modified in StaticFiles. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/StaticFiles.
  SRC project files modified in Antiforgery. Please create branch rel/1.0.4 and merge the changes in C:\gh\Coherence-Patch/.repositories/Antiforgery.
  SRC project files modified in Diagnostics. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/Diagnostics.
  SRC project files modified in Security. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/Security.
  SRC project files modified in MetaPackages. Please create branch rel/1.0.5 and merge the changes in C:\gh\Coherence-Patch/.repositories/MetaPackages.
  SRC project files modified in Mvc. Please create branch rel/1.0.4 and merge the changes in C:\gh\Coherence-Patch/.repositories/Mvc.
  SRC project files modified in Identity. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/Identity.
  Non-SRC project files modified in Entropy. Please commit and merge the changes in C:\gh\Coherence-Patch/.repositories/Entropy.
  SRC project files modified in MusicStore. Please create branch rel/1.0.3 and merge the changes in C:\gh\Coherence-Patch/.repositories/MusicStore.
```

**Comment by pranavkm** [comment]
cc @Eilon - do you think we should generate the actual git commands here (`git checkout ...; git commit -am ..;`)?

**Comment by Eilon** [comment]
@pranavkm - no strong opinion. If it's something that we think is:

1. Easy to get wrong
2. Hard to figure out

Then we should list the exact commands.

**Comment by pranavkm** [comment]
@Eilon it's more about things being mechanical + lots of things to do if you're making a change that affects lots of repos. We could experiment with this and see what people do.

**Pull request merged**
