### PR TITLE
Update the dotnet SDK to 2.2.0-preview1-007796

### PR DESCRIPTION
**Pull request by ryanbrandenburg**

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
Tested locally against Universe.

**Comment by natemcmaster** [comment]
Does it work in Visual Studio too?

**Comment by JunTaoLuo** [comment]
Can we update the runtime as well. It looks like it's set to 2.0.3 right now but we should ingest something newer. The SDK uses 2.1.0-preview1-26001-02 for the runtime for example.

**Comment by ryanbrandenburg** [comment]
Universe doesn't have a good test case, but Logging worked.

**Comment by ryanbrandenburg** [comment]
I'll update the Runtime as a separate thing so we don't delay getting people the SDK.

**Comment by natemcmaster** [comment]
@JunTaoLuo the runtime is determined by repos using dependencies.props and the `<DotNetRuntime>` item group. Example: https://github.com/aspnet/Mvc/blob/dev/build/repo.props#L15-L18

**Comment by JunTaoLuo** [comment]
@natemcmaster Ah right. So what's the purpose of this file: https://github.com/aspnet/BuildTools/blob/dev/files/KoreBuild/config/runtime.version?

**Comment by natemcmaster** [comment]
It's the version that the console tools in KoreBuild need. e.g. NuGetPackageVerifier, KoreBuild.Console, ApiCheck

**Pull request merged**
